### ISSUE TITLE
need to support with typescript 

### ISSUE THREAD

**Issue by webdevlapani** [wojtekmaj/react-datetime-picker#89] opened 2020-01-06 08:19 UTC
I am not able execute with typescript I am getting 
`: error TS7016: Could not find a declaration file for module 'react-datetime-picker'. '/home/loopnix1/client/emgage/engage-ui/node_modules/react-datetime-picker/dist/entry.js' implicitly has an 'any' type.`

**Comment by rwalwood** [comment] 2020-01-09 19:41
I think you'll find this is a duplicate of issue 11 on the codebase: https://github.com/wojtekmaj/react-datetime-picker/issues/11

**Closed** 2020-01-15 10:38 UTC
Labels: duplicate, enhancement
